### ISSUE TITLE
add in other chi-square in tkonfound 

### ISSUE THREAD

**Issue by qinyun-lin** [konfound-project/konfound#21]
Add in options so that users can choose other types of chi-square tests (such as Yate's correction) in the tkonfound function.

**Comment by jrosen48** [comment]
sounds good!

**Comment by jrosen48** [comment]
@qinyun-lin cleaning up old issues. is this still open, or can we close now?

**Comment by qinyun-lin** [comment]
yes, we can close! Thanks!
