### ISSUE TITLE
initial docs for tkonfound() added, but need to be expanded on

### ISSUE THREAD

**Issue by jrosen48** [konfound-project/konfound#23]
these are added to `R/tkonfound.R`, but the documentation is just minimal/a placeholder for now.

**Comment by jrosen48** [comment]
@linqinyu if you have the chance, could you add to these? I have use the royxygen2 conventions right before the function definition (see [`R/konfound.R`](https://github.com/jrosen48/konfound/blob/master/R/konfound.R). When done, just run `devtools::document()`, and it should create the docs (magic of devtools!).

**Comment by linqinyu** [comment]
Sounds good! I will work on this now~:D

**Comment by linqinyu** [comment]
I have added more information to the tkonfound.R (and committed already). But I have some error running "devtools::document()". Maybe you can try it? (I don't want to mess things up.) Let me know if there are any problems!
