### ISSUE TITLE
Add community guidelines

### ISSUE THREAD

**Issue by wjakethompson** [konfound-project/konfound#54]
JOSS review criterion: Community guidelines (https://github.com/openjournals/joss-reviews/issues/5779)

No clear guidelines for external contributions are provided. `usethis::use_tidy_contributing()` provides a good starting point for creating this document (modifications will be needed, but most of the content is relevant).

I would also recommended adding a code of conduct, which can be added using `usethis::use_code_of_conduct()`, and then modified as needed.

**Comment by jrosen48** [comment]
thank you, addressed in https://github.com/konfound-project/konfound/commit/2fbcab46c1efedae07c59acd53a8c6fb027d9d45

**Comment by fabian-s** [comment]
there is no CONTRIBUTING guide, just a code of conduct. this seems to  have been fixed only partially

**Comment by jrosen48** [comment]
Oye, sorry, the CONTRIBUTING.md file exists here: https://github.com/konfound-project/konfound/blob/master/.github/CONTRIBUTING.md

The file we have added notes on using branches for any non-typo edits and the importance of ensuring that all checks successfully pass. We think this will help us as a team to ensure good coding practice (and communicate in writing to open-source contributors about our development process).

We have now mentioned and linked to this file in the README.md file; see here: https://github.com/konfound-project/konfound

**Comment by fabian-s** [comment]
great, thx.  this is usually a top level file but linking in the README is fine as well.
