### ISSUE TITLE
error with thresh_plot output

### ISSUE THREAD

**Issue by jrosen48** [konfound-project/konfound#63]
`model_output <- pkonfound(2, .4, 200, 3, to_return = c("raw_output", "thresh_plot", "corr_plot"))`

returns an error:

```
> model_output <- pkonfound(2, .4, 200, 3, to_return = c("raw_output", "thresh_plot", "corr_plot"))
Error in `purrr::map()` at konfound/R/test_sensitivity.R:109:4:
ℹ In index: 2.
Caused by error in `dplyr::rename()` at konfound/R/helper_plot_threshold.R:14:4:
! Can't rename columns with `beta_threshold`.
✖ Can't convert from `beta_threshold` <double> to <integer> due to loss of precision.
Run `rlang::last_trace()` to see where the error occurred.
```

**Comment by jrosen48** [comment]
@qinyun-lin could you look into this?

**Comment by qinyun-lin** [comment]
if we use "<-", then dd is:  
# A tibble: 1 × 2
  `est_eff <- est_eff` `beta_threshold <- beta_threshold`
                 <dbl>                              <dbl>
1                    2                              0.789

We need to use "=" so that we get dd as:
# A tibble: 1 × 2
  est_eff beta_threshold
    <dbl>          <dbl>
1       2          0.789
