### ISSUE TITLE
JOSS paper edits

### ISSUE THREAD

**Issue by jrosen48** [konfound-project/konfound#81]
- [ x ] 1. Line 149, SE should have a hat and standard error should be standard error estimate. *NOTE: `SE` was a function argument that we have since renamed `std_err. We have changed standard error to estimated standard error.*
- [ x ] 2. Number of digits should be consistent throughout the text: e.g., .568 in line 173 vs. .52 in line 109. *NOTE: This is due to rounding in the underlying code (.52 is equivalent to .520). @fartist would it be preferable to ensure there are a fixed number of digits, i.e. the output would present .520?*
- [ x ] 3. APA style were not followed at multiple places e.g., line 108, line 134. *NOTE: This is addressed apart from K.A. appearing before Frank's last name - we will address this as we make final edits to the paper*.
- [ x ] 4. The statement of need does not address a specific target audience. To me the implied audience is applied researchers, but that's not explicitly stated anywhere. 
- [ x ] 5. The paper does not currently describe how this software compares to existing packages for sensitivity analyses, or mention what other packages are available. *Note: we have notes on this to integrate into the text:

Vanderweel’s E-value package deals with sensitivity for omitted variables for dichotomous outcomes.  It is an improvement on Rosenbaum. We address dichotomous outcomes through case replacement and fragility.
Cinelli’s Robustness index deals with sensitivity of an estimate for continuous outcomes in terms of omitted variables.  ITCV accounts for simultaneous changes in estimates and standard errors.  RIR is an entirely different approach
Many others used simulation based approaches (e.g., Carnegie et al).  E.g. Franks et al.  Baer et al.  Our approach uses closed form expressions to generate a single term representing sensitivity.
Oster’s coefficient of proportionality focuses only on selection into the treatment based on unobservables versus observables necessary to nullify an estimate.  ITCV focuses on relationship of the unobservable to the predictor of interest and  to the outcome. Sensitivity analyses broadly reviewed here.
Frank, K.A., Lin, Q., Xu, R., Maroulis, S.J., Mueller, A. (on-line first). [Quantifying the Robustness of Causal Inferences: Sensitivity Analysis for Pragmatic Social Science](https://www.dropbox.com/s/4vvpvgqhpe2h1rv/Quantifying%20the%20robustness%20of%20causal%20inferences%20as%20published%20sensitivity%20analysis%20for%20pragmatic%20social%20science.pdf?dl=0).  Social Science Research. 110, 102815. ERIC:ED628601

- [ x ] 6. Some of the output in the example uses runs off the edge of the page (this may be a typesetting issue?) *Note: We have mostly addressed this, but there are still a few cases where the output approaches running off the page.*

**Comment by jrosen48** [comment]
another issue that would be helpful to look at - issue 3 above. For some reason, Ken's first initials are appearing in the in-text citations, so they read as e.g. K.A. Frank et al. (2022) instead of Frank et al. (2022). Could you look into how the references are entered in the `.bib` file for the paper?

**Comment by jrosen48** [comment]
@qinyun-lin if you have time, would you be able to look at issue 5? The text above is from Ken, so it just needs to be integrated into the first few paragraphs of the paper (into the introduction of the paper). Aiming to do this by tomorrow.

**Comment by jrosen48** [comment]
I will address 2

**Comment by wwang93** [comment]
> @wwang93 could you look at issue 6 above? You can see the latest version of the paper here: https://github.com/openjournals/joss-papers/blob/joss.05779/joss.05779/10.21105.joss.05779.pdf

I could

**Comment by jrosen48** [comment]
Yep https://github.com/konfound-project/konfound/commit/a2ee5b9068e721e1cf5f442d508be00615918be8 from you addresses issue 6, editing above

**Comment by fartist** [comment]
I am fine with the current version.

  *   [ ? ] 2. Number of digits should be consistent throughout the text: e.g., .568 in line 173 vs. .52 in line 109. NOTE: This is due to rounding in the underlying code (.52 is equivalent to .520). @fartist<https://github.com/fartist> would it be preferable to ensure there are a fixed number of digits, i.e. the output would present .520?



From: Joshua Rosenberg ***@***.***>
Date: Tuesday, February 20, 2024 at 4:46 PM
To: konfound-project/konfound ***@***.***>
Cc: Feeeeeeeeeeng ***@***.***>, Mention ***@***.***>
Subject: Re: [konfound-project/konfound] JOSS paper edits (Issue #81)

Yep a2ee5b9<https://github.com/konfound-project/konfound/commit/a2ee5b9068e721e1cf5f442d508be00615918be8> from you addresses issue 6, editing above

**Comment by jrosen48** [comment]
issues 3 and 5 should now be addressed in https://github.com/konfound-project/konfound/commit/09c675f6d079ca77f067df77902078ff5033867c; waiting for the checks to pass before merging and re-rendering the PDF

**Comment by jrosen48** [comment]
These issues are now all addressed. The paper can be previewed here: https://github.com/openjournals/joss-papers/blob/joss.05779/joss.05779/10.21105.joss.05779.pdf
